---
- name: If not specified, set homelab data directory to $HOME/homelab
  ansible.builtin.set_fact:
    homelab_data_path: "{{ ansible_env.HOME }}/homelab"

- name: Create netboot data directory where the boot files will be stored
  ansible.builtin.file:
    path: "{{ homelab_data_path }}/{{ netboot_data_path }}"
    state: directory
    recurse: true

- name: Download the kickstart files over rsync
  ansible.posix.synchronize:
    mode: pull
    src: "{{ netboot_kickstart_url }}"
    dest: "{{ homelab_data_path }}/{{ netboot_data_path }}/kickstart"

- name: Create SSH key for ansible
  community.crypto.openssh_keypair:
    path: "{{ homelab_data_path }}/ansible_id"
    mode: "0600"
  register: ansible_ssh_key
