---
- name: Install and start server for PXE boot locally
  hosts: localhost
  vars_files:
    - vars/main.yml
  roles:
    - role: 'netboot'
  tags: 'netboot'

- name: Provision the bare-metal servers
  hosts: all
  vars_files:
    - vars/main.yml
  gather_facts: false
  become: true
  roles:
    - role: 'os_install'
  tags: 'os_install'

- name: Teardown containers
  hosts: localhost
  roles:
    - role: 'netboot_teardown'
  tags: 'netboot_teardown'

- name: Install FreeIPA's server
  hosts: freeipa
  become: false
  vars_files:
    - vars/main.yml
  pre_tasks:
    - name: Set FreeIPA hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}.{{ ipaserver_domain }}"
        use: systemd
      become: true
  roles:
    - role: 'freeipa.ansible_freeipa.ipaserver'
      become: true
      state: present
  vars:
    ipaadmin_password: "{{ lookup('ansible.builtin.password', homelab_data_path + '/' + 'passwords' + '/' + 'ipaadmin_password', length=15) }}"
    ipadm_password: "{{ lookup('ansible.builtin.password', homelab_data_path + '/' + 'passwords' + '/' + 'ipadm_password', length=15) }}"
  tags:
    - freeipa
    - freeipa-server

- name: Install FreeIPA's clients
  hosts: kubernetes
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - freeipa_client
  vars:
    ipaadmin_password: "{{ lookup('ansible.builtin.password', homelab_data_path + '/' + 'passwords' + '/' + 'ipaadmin_password', length=15) }}"
    ipadm_password: "{{ lookup('ansible.builtin.password', homelab_data_path + '/' + 'passwords' + '/' + 'ipadm_password', length=15) }}"
  tags:
    - freeipa
    - freeipa-client

- name: Install k3s
  hosts: kubernetes
  become: true
  roles:
    - role: k3s
  tags:
    - k3s
  vars_files:
    - vars/main.yml
