---
# - name: Install sssd config
#   ansible.builtin.template:
#     src: sssd.conf.j2
#     dest: /etc/sssd/sssd.conf
#     mode: "0600"

- name: Set DNS to FreeIPA server
  community.general.nmcli:
    conn_name: "Wired connection 1"
    type: ethernet
    dns4:
      - "{{ hostvars[groups['freeipa'][0]]['ansible_host'] }}"
    state: present
    dns4_ignore_auto: true
  when: inventory_hostname in groups['kubernetes']
  notify: Restart NetworkManager


- name: Install FreeIPA clients
  ansible.builtin.command:
    cmd: "/usr/sbin/ipa-client-install -U \
      --domain={{ ipaserver_domain }} \
      --realm={{ ipaserver_realm }} \
      --server={{ groups['freeipa'][0] }}.{{ ipaserver_domain }} \
      -p admin \
      -w '{{ ipaadmin_password }}' \
      --hostname {{ inventory_hostname}}.{{ ipaserver_domain }} \
      --mkhomedir \
      --no-sshd \
      --force-join"
  retries: 15
  delay: 10
  until: ipa_client_install_output.rc == 0 or ipa_client_install_output.rc == 3
  register: ipa_client_install_output
  changed_when: ipa_client_install_output.rc == 0
  failed_when: ipa_client_install_output.rc not in [0, 3]

- name: Add A records for all clients
  community.general.ipa_dnsrecord:
    ipa_host: "{{ groups['freeipa'][0] }}.{{ ipaserver_domain }}"
    ipa_pass: "{{ ipaadmin_password }}"
    state: present
    zone_name: "{{ ipaserver_domain }}"
    record_name: "{{ inventory_hostname }}"
    record_type: 'A'
    record_value: "{{ ansible_host }}"
  delegate_to: "{{ groups['freeipa'][0] }}"
