---
- name: Prepare netboot working directory
  ansible.builtin.include_tasks:
    file: prepare.yml

- name: Build iPXE
  ansible.builtin.include_tasks:
    file: build-ipxe.yml

- name: Build containers
  ansible.builtin.include_tasks:
    file: build-containers.yml

- name: Prepare containers and the data they use
  ansible.builtin.include_tasks:
    file: prepare-containers.yml

- name: Run containers TFTP and HTTP servers
  ansible.builtin.include_tasks:
    file: run-containers.yml
