---
- name: Send a magic Wake-on-LAN packet all servers
  community.general.wakeonlan:
    mac: "{{ mac }}"
  delegate_to: localhost
  become: false

- name: Wait for system to become reachable
  ansible.builtin.wait_for_connection:
    timeout: "{{ os_install_host_wait_timeout }}"
    connect_timeout: 30
    delay: 0
  vars:
    ansible_host_key_checking: false
  ignore_unreachable: true
