---
- name: Copy container configuration to the data directory
  ansible.builtin.copy:
    src: files/docker
    dest: "{{ netboot_data_path }}"
    mode: "0600"

- name: Copy dnsmasq configuration
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: "{{ netboot_data_path }}/docker/dnsmasq.conf"
    mode: "0600"

- name: Build tftp image
  containers.podman.podman_image:
    name: tftp
    path: "{{ netboot_data_path }}/docker"
    force: true
    build:
      extra_args: --cap-add=NET_ADMIN,NET_RAW
