---
- name: Install dependencies to build iPXE
  ansible.builtin.dnf:
    name:
      - xz-devel
  become: true

- name: Get iPXE source
  ansible.builtin.git:
    repo: "{{ netboot_ipxe_repository_url }}"
    dest: "{{ netboot_data_path }}/ipxe"
    version: HEAD
    clone: true
    update: true

- name: Configure iPXE chainloading
  ansible.builtin.template:
    src: "redirect.ipxe.j2"
    dest: "{{ netboot_data_path }}/ipxe/src/redirect.ipxe"
    mode: "0600"

- name: Build iPXE
  community.general.make:
    chdir: "{{ netboot_data_path }}/ipxe/src"
    target: bin-x86_64-efi/ipxe.efi
    params:
      EMBED: redirect.ipxe
