---
- name: Copy iPXE boot image to container's data directory
  ansible.builtin.copy:
    src: "{{ homelab_data_path }}/{{ netboot_data_path }}/ipxe/src/bin-x86_64-efi/ipxe.efi"
    dest: "{{ homelab_data_path }}/{{ netboot_data_path }}/kickstart/"
    mode: "0664"

- name: Create dynamic iPXE application configuration directory
  ansible.builtin.file:
    path: "{{ homelab_data_path }}/{{ netboot_data_path }}/dynamic_ipxe/boot_config"
    state: directory
    recurse: true

- name: Copy dynamic iPXE configuration application configuration file
  ansible.builtin.copy:
    src: "files/homelab_dynamic_ipxe_config.py"
    dest: "{{ homelab_data_path }}/{{ netboot_data_path }}/dynamic_ipxe/homelab_dynamic_ipxe_config.py"
    mode: "0600"

- name: Copy dynamic iPXE application boot configuration files
  ansible.builtin.template:
    src: "{{ item.key }}"
    dest: "{{ homelab_data_path }}/{{ netboot_data_path }}/dynamic_ipxe/{{ item.value }}"
    mode: "0600"
  with_dict:
    boot_install_coreos.ipxe.j2: boot_config/boot_install_coreos.ipxe
    boot_install_rocky.ipxe.j2: boot_config/boot_install_rocky.ipxe
    homelab_mac_association.yml.j2: homelab_mac_association.yml

- name: Create kickstart files for each FreeIPA machine
  ansible.builtin.template:
    src: "rocky.ks.j2"
    dest: "{{ homelab_data_path }}/{{ netboot_data_path }}/kickstart/{{ hostvars[item]['mac'] }}.ks"
    mode: "0644"
  loop: "{{ query('inventory_hostnames', 'freeipa') }}"

- name: Create ignition files for each CoreOS machine
  ansible.builtin.template:
    src: "coreos.btn.j2"
    dest: "{{ homelab_data_path }}/{{ netboot_data_path }}/kickstart/{{ hostvars[item]['mac'] }}.btn"
    mode: "0644"
  loop: "{{ query('inventory_hostnames', 'kubernetes') }}"

- name: Convert all Butane files to ignition
  ansible.builtin.command:
    cmd: butane {{ item }} -o {{ item | splitext | first }}.ign
  with_fileglob:
    - "{{ homelab_data_path }}/{{ netboot_data_path }}/kickstart/*.btn"
  register: butane_output
  changed_when: butane_output.rc != 0

- name: Set podman SELinux permissions of homelab directory
  ansible.builtin.command:
    cmd: 'podman unshare chown -R 998:996 "{{ item }}"'
  register: pod_unshare_init
  changed_when: pod_unshare_init.rc != 0
  with_items:
    - "{{ homelab_data_path }}/{{ netboot_data_path }}/kickstart"
    - "{{ homelab_data_path }}/{{ netboot_data_path }}/docker_dnsmasq/nginx.conf"

- name: Open DHCP, TFTP and HTTP ports
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
  with_items:
    - dhcp
    - tftp
    - http

- name: Open port 8000
  ansible.posix.firewalld:
    port: "8000/tcp"
    state: enabled


- name: Allow user running podman to bind to ports < 1024
  block:
    - name: Get current net.ipv4.ip_unprivileged_port_start value
      ansible.builtin.shell:
        cmd: sysctl net.ipv4.ip_unprivileged_port_start | grep -o [0-9]*$
      register: sysctl_check_output
      changed_when: sysctl_check_output.rc != 0

    - name: Allow any user to bind on DHCP ports
      ansible.posix.sysctl:
        name: net.ipv4.ip_unprivileged_port_start
        value: 67
        state: present
        reload: true
      become: true
