---
- name: Delete containers if they already exists, otherwise they won't get recreated
  containers.podman.podman_container:
    name: "{{ item }}"
    state: absent
  with_items:
    - homelab_tftp
    - homelab_http

- name: Start TFTP container
  containers.podman.podman_container:
    name: homelab_tftp
    image: localhost/tftp
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - '/home/tw0flower/homelab/netboot/kickstart:/var/lib/tftpboot:z'
    network: host
    recreate: true
    force_restart: true
    state: started

- name: Start HTTP container
  containers.podman.podman_container:
    name: homelab_http
    image: docker.io/nginx
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - '/home/tw0flower/homelab/netboot/kickstart:/var/www/html:z'
      - '/home/tw0flower/homelab/netboot/docker/nginx.conf:/etc/nginx/conf.d/default.conf:z'
    network: host
    recreate: true
    force_restart: true
    state: started
